CREATE TABLE usuario (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255),
    matricula VARCHAR(14) NOT NULL UNIQUE,
    email VARCHAR(255),
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessao (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    usuario_id INTEGER NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (usuario_id) REFERENCES usuario(id) ON DELETE CASCADE
);

CREATE TABLE documento (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(255) NOT NULL
);

CREATE TABLE chunk (
    id SERIAL PRIMARY KEY,
    conteudo TEXT NOT NULL,
    embedding VECTOR(384) NOT NULL,
    documento_id INTEGER NOT NULL,
    FOREIGN KEY (documento_id) REFERENCES documento(id)
);


-- INDEXES WILL BE CREATED ON SQLALCHEMY MODELS
