"""create data tables

Revision ID: 08c159f34a34
Revises: 103a7e79f7d8
Create Date: 2026-09-06 21:35:19.387245

"""
from typing import Sequence, Union

import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '08c159f34a34'
down_revision: Union[str, Sequence[str], None] = '103a7e79f7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=True),
    sa.Column('matricula', sa.String(length=14), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_usuario_matricula'), 'usuario', ['matricula'], unique=True)
    op.create_table('chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('embedding', VECTOR(dim=384), nullable=False),
    sa.Column('documento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['documento_id'], ['documento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='role'), nullable=False),
    sa.Column('sessao_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sessao_id'], ['sessao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mensagem')
    op.drop_table('sessao')
    op.drop_table('chunk')
    op.drop_index(op.f('ix_usuario_matricula'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_table('documento')
    # ### end Alembic commands ###
