"""updating column typing

Revision ID: 866c58b9213d
Revises: b08937cb697e
Create Date: 2026-09-06 15:09:26.158356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '866c58b9213d'
down_revision: Union[str, Sequence[str], None] = 'b08937cb697e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuario', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('usuario', 'nome',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
