"""alter message table

Revision ID: baa63847a22e
Revises: 2beb61e1b580
Create Date: 2026-09-06 23:36:02.438298

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'baa63847a22e'
down_revision: Union[str, Sequence[str], None] = '2beb61e1b580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensagem', sa.Column('criado_em', sa.DateTime(), nullable=False))
    op.add_column('mensagem', sa.Column('atualizado_em', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensagem', 'atualizado_em')
    op.drop_column('mensagem', 'criado_em')
    op.drop_column('mensagem', 'role')
    op.create_index(op.f('chunk_embedding_idx'), 'chunk', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
