"""campo de pagina no chunk

Revision ID: fd84ae0b6dbf
Revises: baa63847a22e
Create Date: 2026-09-09 14:15:20.149470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd84ae0b6dbf'
down_revision: Union[str, Sequence[str], None] = 'baa63847a22e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunk', sa.Column('pagina', sa.Integer(), nullable=False))
    op.drop_index(op.f('chunk_embedding_idx'), table_name='chunk', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('chunk_embedding_idx'), 'chunk', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_column('chunk', 'pagina')
    # ### end Alembic commands ###
